name: Automated Tests for Python Script

on: [push]

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
      - name: Set Up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Test 1
        run: | 
          python3 find_lowest_number.py test_data/test1_input.txt test1_output.txt
          diff test1_output.txt test_data/test1_expected.txt
      - name: Test 2
        run: | 
          python3 find_lowest_number.py test_data/test2_input.txt test2_output.txt
          diff test2_output.txt test_data/test2_expected.txt
      - name: Test 3
        run: | 
          python3 find_lowest_number.py test_data/test3_input.txt test3_output.txt
          diff test3_output.txt test_data/test3_expected.txt
